image: node:12-alpine

stages:
  - deploy

deploy_qa:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    GITHUB_TOKEN: $GITHUB_TOKEN
    API_KEY: $API_KEY_QA
    DEPLOY_ENV: qa
  only:
    - develop
  script:
    - apk add --no-cache git
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - cp configurator/check/qa/narcissus/src/config.js src/
    - npm run deploy

deploy_live:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    GITHUB_TOKEN: $GITHUB_TOKEN
    API_KEY: $API_KEY_LIVE
    DEPLOY_ENV: live
  only:
    - master
  script:
    - apk add --no-cache git
    - git clone https://${GITHUB_TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
    - cp configurator/check/live/narcissus/src/config.js src/
    - npm run deploy
