name: Build and Upload Archive (QA)

on:
  push:
    branches:
      - develop
      - dmou/build-upload-archive

permissions:
  id-token: write
  contents: read

jobs:
  upload-lambda-to-s3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
        aws-region: eu-west-1

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2

    - name: Upload .zip
      id: upload-zip
      run: |
        npm run clean
        npm install &> '/dev/null'
        zip -r lambda_function.zip node_modules/* src/*
        aws s3api put-object --bucket ${{ secrets.AWS_S3_LAMBDA_BUCKET }} --key qa/narcissus/lambda_function.zip

    - name: Send GitHub Action trigger data to Slack workflow
      id: slack-api-notify
      uses: slackapi/slack-github-action@v1.23.0
      with:
         payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.ITS_BOTS_SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
